spring:
  datasource:
    url: jdbc:postgresql://120.25.216.186:5432/ooad
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:
          true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        hbm2ddl:
#          auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false
  redis:
    host: 120.25.216.186
    port: 6379
#    timeout: 3
    password: LInda001
#    pool:
#      minIdle: 1
#      maxIdle: 10
#      maxWait: 3
#      maxActive: 8
#RabbitMQ
  rabbitmq:
 #服务器地址
    host: 120.25.216.186
 #用户名
    username: admin
 #密码
    password: admin

 #端口
    port: 5672
    listener:
      simple:
 #消费者最小数量
        concurrency: 10
 #消费者最大数量
        max-concurrency: 100
 #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
 #启动时是否默认启动容器，默认true
        auto-startup: true
 #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
 #发布重试，默认false
        enabled: true
 #重试时间 默认1000ms
        initial-interval: 1000
 #重试最大次数，默认3次
        max-attempts: 3
 #重试最大间隔时间，默认10000ms
        max-interval: 10000
 #重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s
        multiplier: 1.0



server:
  port: 8888
#  servlet:
#    encoding:
#      charset: utf-8
#      enabled: true
#      force: true
debug: true
